name: Publish
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: npm i -g --force corepack && corepack enable pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build inspector
        run: pnpm inspector:build

      - run: pnpx pkg-pr-new publish
